name: Auto Assign Labels
on:
  issues:
    types: [opened, edited]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Labels Based on Issue Content
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          issue-number: ${{ github.event.issue.number }}
          labels: |
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Severity: Critical') && 'Critical' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Severity: High') && 'High' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Severity: Medium') && 'Medium' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Severity: Low') && 'Low' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Priority: High') && 'High Priority' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Priority: Medium') && 'Medium Priority' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Priority: Low') && 'Low Priority' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Open') && 'Open' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: In Progress') && 'In Progress' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Dev Fixed') && 'Dev Fixed' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Test') && 'Test' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Closed') && 'Closed' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Reopened') && 'Reopened' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Deferred') && 'Deferred' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Invalid') && 'Invalid' || '' }}
            ${{ github.event.issue.body && contains(github.event.issue.body, 'Status: Duplicate') && 'Duplicate' || '' }}
