name: Auto Assign Labels
on:
  issues:
    types: [opened, edited]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Labels Based on Issue Content
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = context.payload.issue.body;
            const labelsToAdd = new Set(["bug"]); // Default label

            // Extract selected values
            const severityMatch = issueBody.match(/Severity:\s*(.*)/);
            const priorityMatch = issueBody.match(/Priority:\s*(.*)/);
            const statusMatch = issueBody.match(/Status:\s*(.*)/);

            // Add labels dynamically
            if (severityMatch) labelsToAdd.add(severityMatch[1].trim());
            if (priorityMatch) labelsToAdd.add(priorityMatch[1].trim() + " Priority");
            if (statusMatch) labelsToAdd.add(statusMatch[1].trim());

            // Apply labels to the issue
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: Array.from(labelsToAdd)
            });
